// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0bYyRgRuKfrPk0dW9UCs7x340bMy3uws',
    appId: '1:809222444332:web:13d9cfd2f41cd6fc00c889',
    messagingSenderId: '809222444332',
    projectId: 'estoque-uvz-2026',
    authDomain: 'estoque-uvz-2026.firebaseapp.com',
    storageBucket: 'estoque-uvz-2026.firebasestorage.app',
    measurementId: 'G-CQ0DHGCB5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdiZQe03fZQ877nEnwhhCzt2VOX9ASjY',
    appId: '1:809222444332:android:46bf8a5090e09cab00c889',
    messagingSenderId: '809222444332',
    projectId: 'estoque-uvz-2026',
    storageBucket: 'estoque-uvz-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOqbIz0qcb9MjbO0EadDmNEioIIx3DUg',
    appId: '1:809222444332:ios:2589eb187aa780fe00c889',
    messagingSenderId: '809222444332',
    projectId: 'estoque-uvz-2026',
    storageBucket: 'estoque-uvz-2026.firebasestorage.app',
    iosBundleId: 'com.example.primeiroProjetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOqbIz0qcb9MjbO0EadDmNEioIIx3DUg',
    appId: '1:809222444332:ios:2589eb187aa780fe00c889',
    messagingSenderId: '809222444332',
    projectId: 'estoque-uvz-2026',
    storageBucket: 'estoque-uvz-2026.firebasestorage.app',
    iosBundleId: 'com.example.primeiroProjetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0bYyRgRuKfrPk0dW9UCs7x340bMy3uws',
    appId: '1:809222444332:web:61455db2bb1360ce00c889',
    messagingSenderId: '809222444332',
    projectId: 'estoque-uvz-2026',
    authDomain: 'estoque-uvz-2026.firebaseapp.com',
    storageBucket: 'estoque-uvz-2026.firebasestorage.app',
    measurementId: 'G-CSHK0ETPCQ',
  );
}
